config/routes.rb
Rails.application.routes.draw do
  get 'jokes/new'
  root :to => 'pages#home'
  resources :users, :only => [:new, :create, :index, :destroy]

  get '/login' => 'session#new'
  post 'login' => 'session#create'
  delete '/login' => 'session#destroy'
  put '/joke/:id/like' => 'jokes#like', as: 'like'
  delete 'joke/:id/like' => 'jokes#unlike'
  get '/dad_jokes' => 'jokes#dad'

  resources :jokes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :jokes
end

app/models/joke.rb
class Joke < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :likes
  def liked?(user)
      !!self.likes.find{|like| like.user_id == user.id}
    end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :joke
  validates :user_id, uniqueness: {scope: :joke_id}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :jokes
  has_many :likes, :dependent => :destroy 
end

app/controllers/concerns/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end

  def check_for_admin
    redirect_to root_path unless @current_user.present? && @current_user.admin?
  end
end

app/controllers/concerns/jokes_controller.rb
class JokesController < ApplicationController
  # before_action :check_for_login

  def index
    @jokes = Joke.all
  end

  def new
    @joke = Joke.new
  end

  def create
    # @current_user.jokes.create joke_params
    joke = Joke.create joke_params
    @current_user.jokes << joke
    redirect_to root_path
  end

  def show
    @joke = Joke.find params[:id]
  end

  def edit
    @joke = Joke.find params[:id]
  end

  def update
    joke = Joke.find params[:id]
    joke.update joke_params
    redirect_to root_path
  end

  def like
    #grabbing the joke
    @joke = Joke.find params[:id]
    #creating a like with that joke and the current user's id
    Like.create(user_id: @current_user.id, joke_id: @joke.id)
    #redirecting them back to that joke
    redirect_to joke_path(@joke)
  end

  def unlike
      @current_user.likes.where(:joke_id => params[:id]).destroy_all
      redirect_to joke_path(params[:id])
  end

  def destroy
    joke = Joke.find params[:id]
    joke.destroy
    redirect_to root_path
  end

  private
  def joke_params
    params.require(:joke).permit(:title, :setup, :punchline)
  end
end

app/controllers/concerns/pages_controller.rb
class PagesController < ApplicationController
  def home
    if @current_user.present?
      @jokes = @current_user.jokes
    else
      @jokes = Joke.all
    end
      @joke = Joke.all.sample
  end
end

app/controllers/concerns/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jokes/edit.html.erb
<h1>Edit joke</h1>

<%= form_for @joke do |f| %>
<div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => 'Funny', :required => true, :class => 'form-control' %>
</div>
<div class="form-group">
  <%= f.label :setup %>
  <%= f.text_field :setup, :placeholder => 'Why did the chicken cross the road', :required => true, :class => 'form-control'  %>
</div>
<div class="form-group">
  <%= f.label :punchline %>
  <%= f.text_field :punchline, :placeholder => 'To get to the other side', :required => true, :class => 'form-control'  %>
</div>

  <%= f.submit "Edit", :class => 'btn btn-success' %>
<% end %>

app/views/jokes/index.html.erb
<h1>All Jokes</h1>

<% @jokes.each do |joke| %>
<%= link_to joke.title, joke_path(joke), :class => 'btn btn-outline-info' %>
<% end %>

app/views/jokes/new.html.erb
<h1>New Joke</h1>

<%= form_for @joke do |f| %>
 <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, :placeholder => 'Funny', :required => true, :class => 'form-control' %>
 </div>

 <div class="form-group">
  <%= f.label :setup %>
  <%= f.text_field :setup, :placeholder => 'Why did the chicken cross the road?', :required => true, :class => 'form-control' %>
 </div>

 <div class="form-group">
  <%= f.label :punchline %>
  <%= f.text_field :punchline, :placeholder => 'To get to the other side', :required => true, :class => 'form-control' %>
 </div>
 
  <%= f.submit "Create Joke!", :class => 'btn btn-warning'  %>
<% end %>

app/views/jokes/show.html.erb
<div class="joke">
  <p><%= @joke.setup %></p>
  <p><%= @joke.punchline %></p>
</div>
<div class="likeButton">
  <% if @current_user.present? %>
    <% if @joke.liked?(@current_user) %>
      <%= button_to "Unlike", like_path(@joke), method: "delete", :class => 'buttonStyle' %>
    <% else %>
      <%= button_to "Like", like_path(@joke), method: "put", :class => 'buttonStyle' %>
    <% end %>
  <% end %>
   <%= pluralize @joke.likes.count, "person" %>
   liked this joke
</div>

<div class="controls">
  <% if @current_user.present? && (@current_user.jokes.include?(@joke) || @current_user.admin?) %>
  <%= link_to "Edit Joke", edit_joke_path(@joke), :class => 'editButton' %>
  <%= button_to "Delete Joke", joke_path(@joke.id), :class => 'deleteButton', :method => "delete", :data => { :confirm => "are you sure" } %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jokes Generater</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
         <%= link_to 'Home', root_path %>
         <% if @current_user.present? %>
           <% if @current_user.admin? %>
             <%= link_to 'All users', users_path %>
           <% end %>
           <%= link_to 'New Joke', new_joke_path %>
           <%= link_to "Log out #{ @current_user.email }", login_path, :method => 'delete' %>
           <%= link_to 'Back', :back  %>
         <% else %>
           <%= link_to 'Sign up', new_user_path %>
           <%= link_to 'Login', login_path %>
           <%= link_to 'Back', :back  %>
         <% end %>
        </div><!-- container -->
      </nav>
    <div class="container">

     <%= yield %>

    </div>
  </body>
</html>

app/views/pages/home.html.erb
<% if @current_user.present? %>
  <h1>Your Jokes</h1>
  <p>You are currently logged in as <%= @current_user.email %></p>
<% else %>
  <h1>All Jokes</h1>
<% end %>

<% @jokes.each do |joke| %>
<%= link_to joke.title, joke_path(joke), :class => 'btn btn-outline-info' %>
<% end %>

<% if @current_user.present? %>
  <p>
    <%= link_to "All jokes", jokes_path, :class => 'btn btn-success' %>
  </p>
<% end %>
<br>


<button  id="getDadJoke" class="btn btn-secondary">Random Dad Joke</button>
<p id="dadJoke" style="display:none"><%= DadJokes.random  %></p>
<br>

<button id="getUserJoke" class="btn btn-secondary">Random User Joke</button>
<p id="userJoke" style="display:none">
  <%= @joke.setup %><br>
  <%= @joke.punchline%><br>
  by user:
<span class="userEmail"><%= @joke.user.try :email %></span>
</p><br>
<button onclick="location.reload()">Reload</button>

app/views/session/new.html.erb
<h2>Log In</h2>

<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>

  <div class="form-group">
    <%= label_tag :email %>
    <%= email_field_tag :email, nil, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :password %>
    <%= password_field_tag :password, nil, :class => 'form-control' %>
  </div>

  <%= submit_tag "Sign in", :class => 'btn btn-success' %>
<% end %>

app/views/users/faq.erb
  <h1>stay awake</h1>
<p>beers tonight</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
 <p>
   <%= link_to user.email %>
 </p>


 <div class="dashboard">
   <% if @current_user.admin? %>
     <%= link_to "Delete Account", user_path(user.id), :method => "delete", :data => { :confirm => "are you sure" } %>
   <% end %>
 </div>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<% if @user.errors.any? %>
  <ol>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ol>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>
  </div>

    <%= f.submit "Sign up!", :class => 'btn btn-success' %>
<% end %>